---
- hosts: Ubuntu22 
  gather_facts: True
  roles:
    - ubuntu_base

- hosts: Docker
  gather_facts: False
  roles:
    - docker

- hosts: Nginx
  gather_facts: True
  roles:
    - nginx
- hosts: filebeat
  gather_facts: True
  become: yes
  become_user: root
  become_method: su
  become_exe: sudo su
  roles:
    - filebeat_install
